Fixes MSBuild (non-VS) compile issue
Non-entry Main(...) method renamed to Run(...). Avoids error message:
"Program.cs(13,28): error CS0028: 'Program.Main(string)' has the wrong
signature to be an entry point"